server:
  port: 8888

spring:
  application:
    name: config-server
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:./config,classpath:/config

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,env