server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # CONFIGURACIÓN GLOBAL DE CORS
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:4200"
              - "http://127.0.0.1:4200"
              - "https://helpcore.com"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      # RUTAS DEL GATEWAY
      routes:
        # AUTH SERVICE
        - id: auth-service
          uri: http://localhost:8081  # Cambia por el puerto de tu auth service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
          metadata:
            cors:
              allowedOriginPatterns: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
              allowCredentials: true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# EUREKA CLIENT
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# ===== JWT CONFIGURATION =====
jwt:
  secret: QmFzZTY0RW5jb2RlZEtleVNlZ3VyYUV4YW1wbGVEYXRhIQ==
  expiration: 60000

# ===== LOGGING =====
logging:
  level:
    com.ticketing.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: INFO
    org.springframework.web.cors: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# ===== MANAGEMENT (ACTUATOR) =====
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

# CONFIGURACIONES COMENTADAS PARA DESPUÉS
#spring.redis:
#  host: localhost
#  port: 6379
#  timeout: 2000ms
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      auth-service-cb:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        failureRateThreshold: 50
#        waitDurationInOpenState: 30s
#        permittedNumberOfCallsInHalfOpenState: 3